### ISSUE TITLE
merge_depth_cam or merged_depth_cam

### ISSUE THREAD

**Issue by thieri** [HWiese1980/merge_depth_cam#1]
Hi there, thanks for your effort.
I am haveing difficulties cause of "nameing" of package.
merge_depth_cam
merged_depth_cam
seems to be mixed up some times, and this produces compile-errors.

(Maybe it is my mistake, so feel free to correct me, if necessary)

**Comment by HWiese1980** [comment]
True, I'm sorry about this. Sadly though, I am currently unable to fix it as I've moved on to other topics and don't have access to hardware necessary to actually try and test code changes. 

Contributions however are very welcome and I'll see what I can incorporate into the repo!!

**Comment by HWiese1980** [comment]
Oh and sorry that I took so long to get back to you... as I said, priorities have changed. And I must admit that I've seen this issue just now...

**Comment by thieri** [comment]
Thanks for coming Back at all. Good luck with your Projects.

**Comment by thieri** [comment]
Author switched to other Project T_T

**Comment by HWiese1980** [comment]
Thank you!

For other readers, once again: **Contributions are still welcome! Feel free to fork!**
